### ISSUE TITLE
error during compile in dot net 8.0

### ISSUE THREAD

**Issue by ilgrandetia** [Montesuma80/3cx-web-API#38]
Hi Montesuma80, I tried to compile using dot net 8.0 but gave me this error:

`/root/3cx-web-API/update.cs(16,30): error CS0161: 'update.updateid(string, string)': not all code paths return a value [/root/3cx-web-API/WebAPICore.csproj]
    Notices: 16
    Errors: 1`

I have correct into WebAPICore.csproj the version to "net8.0" and the other two params like describe in README.

Need to do something else?

The 3CX version is V20, specifically 20.0 Update 1 (Build 731 Release).

Kind regards

**Comment by gloriapbx** [comment]
Yes, i have the same issue as you have. Anyone have solution?
